[project]
name = "aiml-engineer-codebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sureshssh", email = "hooli9060@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gitsource>=0.0.5",
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.24.0",
    "python-frontmatter>=1.3.0",
    "requests>=2.34.2",
]

[project.scripts]
aiml-engineer-codebase = "aiml_engineer_codebase:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
